##--------------------------------------------------------------------
## rmqtt-bridge-ingress-nats
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/bridge-ingress-nats.md

[[bridges]]
# Whether to enable
enable = true
# Bridge name
name = "bridge_nats_1"
# The address of the NATS broker that the client will connect to using plain TCP.
# In this case, it's connecting to the local broker at port 4222.
servers = "nats://127.0.0.1:4222"
#servers = "tls://127.0.0.1:4433"

# Consumer name prefix
consumer_name_prefix = "consumer_1"

## See https://github.com/nats-io/nats.rs/blob/main/async-nats/src/options.rs
#no_echo = true
#ping_interval = "60s"
#connection_timeout = "10s"
#tls_required = true
#tls_first = true
#root_certificates = ""
#client_cert = ""
#client_key = ""
#sender_capacity = 256
#auth.jwt = ""
#auth.jwt_seed = ""
#auth.nkey = ""
#auth.username = ""
#auth.password = ""
#auth.token = ""

[[bridges.entries]]

remote.topic = "test1"
#remote.group = "group1"

local.topic = "local/topic1/ingress/${remote.topic}"

## Choose 0, 1, 2, or not set (follow message QoS, i.e. user-defined properties "qos")
##
## Value: 0 | 1 | 2
#local.qos = 1

## Choose true or false, or not set (follow message Retain, i.e. user-defined properties "retain")
##
## Value: true | false
## Default: false
#local.retain = false

## Allow forwarding of empty messages
##
## Value: true | false
## Default: true
#local.allow_empty_forward = false

[[bridges.entries]]
remote.topic = "test2"
#remote.group = "group2"

local.topic = "local/topic2/ingress"
#local.qos = 0
#local.retain = false


