[package]
name = "rmqtt-p2p-messaging"
version.workspace = true
description = "An rmqtt plugin that provides point-to-point (P2P) messaging support, enabling direct message delivery between clients using configurable topic patterns."
repository = "https://github.com/rmqtt/rmqtt/tree/master/rmqtt-plugins/rmqtt-p2p-messaging"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmqtt = { workspace = true, features = ["plugin"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
async-trait.workspace = true
log.workspace = true
serde_json.workspace = true
anyhow.workspace = true


